### ISSUE TITLE
Aufzählungslisten im Editor

### ISSUE THREAD

**Issue by henning-meyer79** [ase379/ekit#11]
Wird das Icon Aufzählungsliste ausgeführt wird zwar ein Bullet angelegt, durch Drücken von Enter wird es wieder gelöscht. Es wird kein weiterer Bullet wie in Word angelegt.

![grafik](https://user-images.githubusercontent.com/57505718/119625700-c5a7f000-be0a-11eb-9626-12c393deea42.png)

**Comment by ase379** [comment]
Wird in Word in einem ListItem (Punkt oder Zahl) Enter gedrückt, so wird das item entfernt.
